// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtdacpxpywcihtqtuuen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZGFjcHhweXdjaWh0cXR1dWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5MTkxMDIsImV4cCI6MjA1OTQ5NTEwMn0.fyL6DqVDu8tRR-eKfslH2GyJo2D0KtxDsDed7mI1iJw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);